name=FastRGB
version=1.0.1
author=Ben Stokman
maintainer=Ben Stokman <ben.stokman@protonmail.com>
sentence=Simple, modern, object-oriented library for controlling addressible RGB strips.
paragraph=Simple, modern, object-oriented library for controlling addressible RGBs strips. Contains many nice features including partitioning & re-arranging series of colors, chainable effect interface with example effects, and more.
category=Display
url=https://git.benstokman.me/benjistokman/FastRGB
architectures=avr,renesas_uno
