name=FastRGB
version=1.0.0
author=Ben Stokman
maintainer=Ben Stokman <ben.stokman@protonmail.com>
sentence=Simple, modern, object-oriented library for controlling addressible RGB strips.
paragraph=Simple, modern, object-oriented library for controlling addressible RGBs strips.
category=Display
url=https://git.benstokman.me/benjistokman/FastRGB
architectures=avr,renesas_uno